version: "3.7"
services:
  banfox_postgres:
    image: "postgres:11"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secretpass

  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379

volumes:
  banfox:
  postgres_data:
