version: "3.7"
services:
  banfox_postgres:
    image: "postgres:11"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secretpass
      - POSTGRES_USER=postgres

  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379

  mongodb:
    image: mongo:3.4-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  banfox:
  postgres_data:
